#!/usr/bin/env bash

# shellcheck source=utils.bash
. "$HOME/.githooks/utils.bash"

run_php_tests() {
	local -a delta
	print_log "Running php tests"
	mapfile -t delta < <(git diff --name-only --cached)
	for line in "${delta[@]}"; do
		local basename_without_ext
		file="$(basename $line)"
		basename_without_ext="${file%.*}"

		test_file="$(find . -name "$basename_without_ext*" -not -path "./vendor*" -not -path "./tests*" | grep "Test.php")"

		if [[ -n $test_file ]]; then
			print_log "Found test file: $test_file"
			if [[ -f $PWD/vendor/bin/phpunit ]]; then
				print_log "Found phpunit"
				print_log "Running test"
				"$PWD/vendor/bin/phpunit" "$test_file"
			fi
		fi
	done
}

run_go_tests() {
	if hash go >/dev/null; then
		print_log "Running unit tests"
		go test ./... | colorize_output
	fi
}

main() {
	print_log "Running pre-commit hook"
	if [[ -f ./main.go ]]; then
		run_go_tests
	fi

	if [[ -f ./composer.json ]]; then
		run_php_tests
	fi
}

main
